import { Template, CaptionStyle } from './types';
import { Film, Music, Zap, Heart, Camera, Globe } from 'lucide-react';
import React from 'react';

export const TEMPLATES: Template[] = [
  {
    id: 'cinematic-vlog',
    name: 'Cinematic Vlog',
    description: 'High-quality travel and lifestyle aesthetics.',
    stylePrompt: 'Cinematic 4k shot, vlog style, golden hour lighting, travel aesthetic, highly detailed, smooth camera motion',
    icon: 'Camera',
    gradient: 'from-orange-500 to-pink-500',
  },
  {
    id: 'desi-beats',
    name: 'Desi Beats',
    description: 'Energetic, colorful, Bollywood inspired.',
    stylePrompt: 'Bollywood style music video, vibrant colors, energetic motion, indian cultural elements, festivity, 4k high quality',
    icon: 'Music',
    gradient: 'from-red-500 to-yellow-500',
  },
  {
    id: 'moody-lyrics',
    name: 'Moody Lyrics',
    description: 'Dark, neon, emotional vibe for poetry.',
    stylePrompt: 'Dark moody atmosphere, neon lights, urban night street, rain reflections, slow motion, emotional, 4k',
    icon: 'Heart',
    gradient: 'from-purple-600 to-blue-600',
  },
  {
    id: 'tech-reveal',
    name: 'Tech Reveal',
    description: 'Clean, modern, sleek futuristic look.',
    stylePrompt: 'Futuristic product reveal, clean white studio lighting, sleek surfaces, macro shot, technology, 4k',
    icon: 'Zap',
    gradient: 'from-cyan-500 to-blue-500',
  },
  {
    id: 'classic-film',
    name: 'Classic Film',
    description: 'Vintage grain, black and white or sepia.',
    stylePrompt: 'Vintage film look, film grain, 16mm aesthetic, nostalgia, classic cinema, soft lighting',
    icon: 'Film',
    gradient: 'from-stone-500 to-stone-700',
  },
  {
    id: 'global-news',
    name: 'Global News',
    description: 'Broadcast quality, breaking news style.',
    stylePrompt: 'Breaking news studio background, broadcast graphics style, professional, blue and globe themes, 4k',
    icon: 'Globe',
    gradient: 'from-blue-700 to-slate-800',
  },
];

// Base Fonts
const FONTS = {
    IMPACT: 'Impact, sans-serif',
    INTER: 'Inter, sans-serif',
    COURIER: 'Courier New, monospace',
    ARIAL_BLACK: 'Arial Black, sans-serif',
    VERDANA: 'Verdana, sans-serif',
    GEORGIA: 'Georgia, serif',
    HELVETICA: 'Helvetica, sans-serif',
};

export const CAPTION_STYLES: CaptionStyle[] = [
  {
    id: 'hormozi',
    name: 'The Hormozi',
    font: FONTS.IMPACT,
    fontSize: 48,
    fontWeight: 900,
    color: '#FFD700',
    strokeColor: '#000000',
    strokeWidth: 4,
    paddingX: 0,
    paddingY: 0,
    borderRadius: 0,
    animation: 'pop',
    highlightColor: '#FFFFFF',
    highlightBgColor: 'transparent'
  },
  {
    id: 'karaoke-pro',
    name: 'Karaoke Pro',
    font: FONTS.INTER,
    fontSize: 40,
    fontWeight: 800,
    color: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 2,
    paddingX: 0,
    paddingY: 0,
    borderRadius: 0,
    animation: 'karaoke',
    highlightColor: '#00FF00'
  },
  {
    id: 'retro-vcr',
    name: 'Retro VCR',
    font: FONTS.COURIER,
    fontSize: 34,
    fontWeight: 400,
    color: '#FFFFFF',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingX: 10,
    paddingY: 4,
    borderRadius: 0,
    animation: 'typewriter',
    strokeColor: '#00FF00',
    strokeWidth: 1,
  },
  {
    id: 'glitch-pop',
    name: 'Glitch Pop',
    font: FONTS.ARIAL_BLACK,
    fontSize: 42,
    fontWeight: 900,
    color: '#FF00FF',
    strokeColor: '#00FFFF',
    strokeWidth: 2,
    paddingX: 0,
    paddingY: 0,
    borderRadius: 0,
    animation: 'shake',
    highlightColor: '#FFFFFF'
  },
  {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    font: FONTS.INTER,
    fontSize: 30,
    fontWeight: 500,
    color: '#FFFFFF',
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingX: 16,
    paddingY: 6,
    borderRadius: 8,
    animation: 'fade',
  },
  {
    id: 'mr-beast',
    name: 'The Beast',
    font: FONTS.ARIAL_BLACK,
    fontSize: 52,
    fontWeight: 900,
    color: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 6,
    shadowColor: 'rgba(0,0,0,0.8)',
    paddingX: 0,
    paddingY: 0,
    borderRadius: 0,
    animation: 'bounce',
    highlightColor: '#FF0055'
  },
  {
    id: 'highlight-marker',
    name: 'Highlighter',
    font: FONTS.VERDANA,
    fontSize: 36,
    fontWeight: 700,
    color: '#000000',
    paddingX: 4,
    paddingY: 2,
    borderRadius: 4,
    animation: 'highlight-word',
    highlightBgColor: '#FFFF00'
  },
  {
    id: 'news-ticker',
    name: 'News Ticker',
    font: FONTS.HELVETICA,
    fontSize: 30,
    fontWeight: 600,
    color: '#FFFFFF',
    backgroundColor: '#0000CC',
    paddingX: 20,
    paddingY: 10,
    borderRadius: 0,
    animation: 'slide',
  }
];

export const ICON_MAP: Record<string, React.ReactNode> = {
  Camera: <Camera className="w-6 h-6" />,
  Music: <Music className="w-6 h-6" />,
  Heart: <Heart className="w-6 h-6" />,
  Zap: <Zap className="w-6 h-6" />,
  Film: <Film className="w-6 h-6" />,
  Globe: <Globe className="w-6 h-6" />,
};